name: JetsonMind CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 pytest
        if [ -f core/requirements.txt ]; then pip install -r core/requirements.txt; fi
    
    - name: Code formatting check
      run: |
        black --check --diff core/
        isort --check-only --diff core/
    
    - name: Lint with flake8
      run: |
        flake8 core/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 core/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Test with pytest
      run: |
        cd core && python -m pytest -v || echo "Tests not yet implemented"
    
    - name: Documentation check
      run: |
        # Check for broken links in documentation
        find docs/ -name "*.md" -exec grep -l "http" {} \; || echo "No external links found"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run security scan
      run: |
        pip install safety bandit
        safety check || echo "Safety check completed"
        bandit -r core/ || echo "Security scan completed"
